### PR TITLE
feat: service not available

### PR DESCRIPTION
**Pull request by melniiv**
## Description

image

## Context

[jira-id](https://helsinkisolutionoffice.atlassian.net/browse/<jira-id>)

### CODE REVIEW

**Comment by terovirtanen** [comment]
**YOUTH-MEMBERSHIP-UI branch is deployed to platta: https://youth-membership-ui-pr325.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH-MEMBERSHIP-UI branch is deployed to platta: https://youth-membership-ui-pr325.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**YOUTH-MEMBERSHIP-UI branch is deployed to platta: https://youth-membership-ui-pr325.dev.hel.ninja** :rocket::rocket::rocket:

**Review by jannetalvio — APPROVED** [review]
As specified.

**Pull request merged**
